include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - example/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - prefer_final_fields
    - sort_pub_dependencies

